apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: flux-system
spec:
  interval: 15m
  timeout: 5m
  targetNamespace: telemetry-system
  chart:
    spec:
      chart: grafana-operator
      version: "v5.19.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    watchNamespaces: "telemetry-system"
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
