apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: telemetry-system
  labels:
    dashboards: "grafana"
spec:
  config:
    auth:
      disable_login_form: "false"
    auth.anonymous:
      enabled: "false"
    security:
      admin_user: admin
      admin_password: datum123
    unified_alerting:
      enabled: "true"
      alertmanager_config_from_datasources: "true"
    alerting:
      enabled: "false"  # Disable legacy alerting in favor of unified alerting
  service:
    spec:
      type: NodePort
      ports:
        - name: grafana-http
          port: 3000
          targetPort: 3000
          nodePort: 30000
          protocol: TCP
  deployment:
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:12.2.0
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
