apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: flux-system
spec:
  interval: 15m
  timeout: 10m
  targetNamespace: telemetry-system
  chart:
    spec:
      chart: promtail
      version: "6.16.6"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Configure Promtail to send logs to Loki
    config:
      lokiAddress: http://telemetry-system-loki.telemetry-system.svc.cluster.local:3100/loki/api/v1/push
      clients:
        - url: http://telemetry-system-loki.telemetry-system.svc.cluster.local:3100/loki/api/v1/push

    # DaemonSet configuration - runs on every node
    daemonset:
      enabled: true

    # Resource configuration for test environment
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

    # Service monitor disabled for test environment
    serviceMonitor:
      enabled: false

    # Default scrape configs for Kubernetes logs
    defaultVolumes:
      - name: run
        hostPath:
          path: /run/promtail
      - name: containers
        hostPath:
          path: /var/lib/docker/containers
      - name: pods
        hostPath:
          path: /var/log/pods

    defaultVolumeMounts:
      - name: run
        mountPath: /run/promtail
      - name: containers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: pods
        mountPath: /var/log/pods
        readOnly: true

    # Scrape configuration
    configmap:
      enabled: true
