# Configure the cluster's audit log policy.
#
# See: https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/
apiVersion: audit.k8s.io/v1
kind: Policy
# Only capture the ResponseComplete stage. This stage will include the full
# request / response body when the RequestResponse level is used.
omitStages:
  - RequestReceived
  - ResponseStarted
  - Panic
rules:
# Skip logging for non-resource URLs (health checks, metrics, etc.)
- level: None
  nonResourceURLs:
    - /healthz*
    - /readyz*
    - /livez*
    - /metrics
    - /metrics/*
    - /openapi*
    - /openapi/v3
    - /version*
    - /apis
    - /api*

# Skip logging for leases (leader election, node heartbeats)
- level: None
  resources:
    - group: coordination.k8s.io
      resources:
        - leases

# Skip logging for events (very noisy)
- level: None
  resources:
    - group: ""
      resources:
        - events

# Skip logging for endpoint slices (frequent updates)
- level: None
  resources:
    - group: discovery.k8s.io
      resources:
        - endpointslices

# Skip logging for node status updates
- level: None
  resources:
    - group: ""
      resources:
        - nodes/status

# Skip logging for service account token requests
- level: None
  resources:
    - group: ""
      resources:
        - serviceaccounts/token

# Skip noisy authentication / authorization requests
- level: None
  resources:
    - group: authorization.k8s.io
      resources:
        - subjectaccessreviews
        - selfsubjectaccessreviews
        - selfsubjectrulesreviews
        - localsubjectaccessreviews
    - group: authentication.k9s.io
      resources:
        - tokenreviews

# Skip logging for system:nodes and system:serviceaccounts
- level: None
  users:
    - system:kube-scheduler
    - system:kube-controller-manager
    - system:kube-proxy
  verbs:
    - get
    - list
    - watch

# Skip logging for kubelet read operations
- level: None
  userGroups:
    - system:nodes
  verbs:
    - get
    - list
    - watch

# Skip logging for watch requests (very noisy, long-lived connections)
- level: None
  verbs:
    - watch

# Log modify operations with full request / response
- level: RequestResponse
  verbs:
  - create
  - update
  - patch
  - delete

# Log everything else at Request level
- level: Request
