apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-csi-driver
  namespace: cert-manager
spec:
  interval: 1m
  chart:
    spec:
      chart: cert-manager-csi-driver
      version: v0.10.3
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    # Minimal configuration for development - using chart defaults