apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoria-metrics-datasource
  namespace: telemetry-system
  labels:
    dashboards: "grafana"
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-telemetry-system-vm-victoria-metrics-k8s-stack.telemetry-system.svc.cluster.local:8428
    uid: victoria-metrics-datasource
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "30s"
